### ISSUE TITLE
Documenting usage

### ISSUE THREAD

**Issue by jrbe228** [kenmuse/arc-windows-runner#3]
How would I set up a values.yml file similar to the example [here](https://www.kenmuse.com/blog/windows-runners-on-actions-runner-controller/), to enable access to the docker daemon? Or perhaps that is included with container hooks. 

Separately it would be valuable to have a Win Server 2019 (10.0.19045-compatible) version available in this repo.

**Comment by kenmuse** [comment]
I'm assuming from the context that you're trying to find solutions to allow you to build Windows images from within a containerized runner.  If that's not correct -- let me know!

Unfortunately, Windows doesn't yet provide support for Docker in Docker (DinD). Using DinD relies on nested container support, which AFAIK is still not implemented in Windows. As a result, Docker doesn't provide a Windows `dind` image and [notes](https://hub.docker.com/_/docker#:~:text=docker%3A%3Cversion%3E%2Dwindowsservercore-,Unfortunately,-%2C%20Windows%20does%20not) that in their documentation. While there may be ways to try to make that work by installing Docker Desktop centrally on the node, I haven't personally tried that (and it would open up some serious security risks since all of the containers would share a privileged resource). 

If you need to build Windows images, a full VM will typically be necessary (esp. to do that securely). The GitHub hosted runners have support for that built in (which is why I'm using that for my sample image). If you want to see how that is implemented, the source code for building those disk images is [here](https://github.com/actions/runner-images/tree/main/images/windows).

While I do include the container hooks in the build, I have since gone much deeper into the runner code. I don't think there are any cases where those will get invoked. Reading that code and its documentation, those are only intended to support job and service containers. Those two features are limited to Linux runners and not supported with Windows, so the code shouldn't be invoked. As a result, I believe that code could be safely omitted from the image.

**Comment by jrbe228** [comment]
Correct, I'm trying to build Windows images from within a containerized runner on Kubernetes. We are currently building images on Windows VMs (self-hosted or Github-provided) which works. Ideally we would prefer to build in containers. I saw the Docker CLI tooling in your Dockerfile and misunderstood the use case. Your CLI tooling was only included for feature parity with the Windows Runner VM template. 

This may be the wrong forum for further discussion, but I'll try anyway :) I see a number of approaches online which I may attempt next month. Let me know if you have any insight. If any of the following work, it then becomes possible to combine them with ARC. 

1. BuildKit for Windows containers is now in prerelease: 
https://github.com/moby/buildkit/blob/master/docs/windows.md
Containerd is of course a prereq, so I would either need to have that containerized, or mount the socket to BuildKit container. 

2. If there are problems with the (very experimental) release of Windows BuildKit, the following might work: 
Docker CLI ---> containerd-shim ---> containerd socket mount ---> containerd
- Docker CLI tooling installed in a Runner container such as yours.
- containerd-shim added to the container, which should translate `docker` commands to their containerd equivalent. 
- mount the socket from the underlying k8s worker node
- Build commands execute in containerd on the worker node
Obviously lots of security concerns with this approach. Just a theory. 

3. If all else fails, run the Docker Daemon as HostProcess container
https://lippertmarkus.com/2022/04/22/win-img-docker-hostprocess-k8s/
Note this author has other articles on refactoring Windows Dockerfiles for compatibility with Linux Buildkit (remove the RUN directives), but we would prefer to avoid an enterprise-wide refactoring initiative.

**Comment by kenmuse** [comment]
In terms of what is possible, I think you're exploring along the right lines. The various approaches require working outside of the container system on the host to get around the nested container issues. You can then mount the Docker pipe into the containers to get access. As you mentioned, that does come with security concerns. From the [K8S docs](https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/):

> HostProcess containers run as a process on the host and do not have any degree of isolation other than resource constraints imposed on the HostProcess user account. Neither filesystem or Hyper-V isolation are supported for HostProcess containers.

In the article you referenced, the author limits the approach to a single node to help restrict some of what an exploit could do.

I would generally recommend sticking with a hosted runner for that use case (and do any work that can be handled on Linux on other runners to save time/costs). This provides you with scale. If you don't need the network access, you also get a network-isolated VM (which improves security). If you need internal network access, consider the larger hosted runners; they support assigned IP address ranges and Azure VNET injection.

If you're doing self-hosted, a full VM becomes the safest and most performant approach if that's an option for you. You'll probably want to use the job hooks to perform cleanup before and after builds if the instance is long-lived. If you want the instance to be ephemeral, you could customize ARC (and/or K8S) or create scripts to deploy VMs and configure a runner. If you are automating VMs, consider using [JIT](https://docs.github.com/en/enterprise-cloud@latest/actions/security-guides/security-hardening-for-github-actions#using-just-in-time-runners), which provides the full configuration for a single ephemeral runner (which can be included when you're provisioning/configuring the VM).

Hope those ideas help!
